name: enObject
favicon: null
layout_spectrum: 0.6285317027941346
typography_spectrum: 0.09976621251553297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12559888884425163
  lightness: 0.026951277628540993
  saturation: 0.43795666587539017
  rhythmicContrast: 0.5309053892269731
purpose: []
